import type { AxiosAdapter, AxiosResponse, InternalAxiosRequestConfig } from 'axios';

import { leaveApi } from '../../features/leave/api/leaveApi';
import { api, axiosInstance, postMultipart } from '../client';

/**
 * Transport-level tests for the shared axios client, focused on how a multipart
 * upload is handed to the networking layer.
 *
 * ## Why this matters
 *
 * A multipart boundary is generated by the platform's networking layer, not by
 * JavaScript. The header handling is therefore easy to get wrong in two opposite ways:
 *
 * - Hardcoding `Content-Type: multipart/form-data` omits the boundary, so PHP/Laravel
 *   cannot parse the parts.
 * - Omitting the header entirely leaves the instance's `application/json` default in
 *   place, and axios's `transformRequest` then JSON-serializes the `FormData` body —
 *   turning the upload into a string and destroying the file parts.
 *
 * `postMultipart` clears the header to `undefined`, which avoids both. These tests run
 * the **real** client against a capturing adapter, so they assert on the exact config
 * that would reach the network layer rather than on a mock's arguments.
 */

/**
 * A schema-valid `LeaveRequestResource`.
 *
 * The adapter below answers every request with this body. It must satisfy
 * [`leaveRequestSchema`](src/features/leave/validation/apiSchemas.ts:1) because the
 * real [`leaveApi.create`](src/features/leave/api/leaveApi.ts:1) now validates its
 * response at the boundary — an invalid fixture would throw before the transport
 * assertions this file exists for.
 */
const LEAVE_REQUEST_FIXTURE = {
    id: 1,
    company_id: 1,
    employee_id: 42,
    leave_type_id: 2,
    leave_type: null,
    employee: null,
    start_date: '2026-09-20',
    end_date: '2026-09-20',
    start_session: 'full_day',
    end_session: 'full_day',
    total_days: '1.00',
    reason: null,
    attachment: null,
    attachments: [],
    status: 'pending',
    approved_by: null,
    approved_at: null,
    rejected_by: null,
    rejected_at: null,
    rejection_reason: null,
    admin_notes: null,
    approver: null,
    rejecter: null,
    created_at: '2026-09-19T00:00:00+10:00',
    updated_at: '2026-09-19T00:00:00+10:00',
};

/** The config axios actually dispatched, captured by the stub adapter. */
let captured: InternalAxiosRequestConfig | null = null;

let originalAdapter: typeof axiosInstance.defaults.adapter;

beforeEach(() => {
    captured = null;
    originalAdapter = axiosInstance.defaults.adapter;

    const capturingAdapter = (async (config: InternalAxiosRequestConfig) => {
        captured = config;

        return {
            data: LEAVE_REQUEST_FIXTURE,
            status: 200,
            statusText: 'OK',
            headers: {},
            config,
        } as AxiosResponse;
    }) as unknown as AxiosAdapter;

    axiosInstance.defaults.adapter = capturingAdapter;
});

afterEach(() => {
    axiosInstance.defaults.adapter = originalAdapter;
});

function buildFormData(): FormData {
    const formData = new FormData();

    formData.append('employee_id', '42');

    return formData;
}

describe('postMultipart', () => {
    it('transmits the body as FormData rather than JSON-serializing it', async () => {
        const formData = buildFormData();

        await postMultipart('/leave-requests', formData);

        expect(captured).not.toBeNull();
        // The decisive guarantee: the payload is still a FormData object, so the
        // platform can encode it with a boundary. A string here would mean the file
        // parts were lost.
        expect(captured?.data).toBeInstanceOf(FormData);
        expect(typeof captured?.data).not.toBe('string');
    });

    it('does not hardcode a boundary-less multipart Content-Type', async () => {
        await postMultipart('/leave-requests', buildFormData());

        // The previous implementation sent the literal "multipart/form-data" with no
        // boundary, which Laravel rejects. Clearing the header avoids that.
        expect(captured?.headers.getContentType()).not.toBe('multipart/form-data');
    });

    it('still sends JSON bodies with an application/json Content-Type', async () => {
        await api.post('/leave-requests', { employee_id: 42 });

        // Regression guard: the fix must not affect ordinary JSON requests.
        expect(typeof captured?.data).toBe('string');
        expect(captured?.headers.getContentType()).toContain('application/json');
    });
});

describe('leave request with an attachment (integration)', () => {
    it('sends employee_id and the attachment as multipart, not JSON', async () => {
        // Exercises the real leaveApi → real client → capturing adapter path.
        const appendSpy = jest.spyOn(FormData.prototype, 'append');

        await leaveApi.create({
            employee_id: 42,
            leave_type_id: 2,
            start_date: '2026-09-20',
            end_date: '2026-09-20',
            attachments: [
                { uri: 'file:///tmp/cert.pdf', name: 'cert.pdf', mimeType: 'application/pdf' },
            ],
        });

        expect(captured).not.toBeNull();
        expect(captured?.data).toBeInstanceOf(FormData);

        // The scalar fields survive the multipart branch...
        expect(appendSpy).toHaveBeenCalledWith('employee_id', '42');
        // ...and the file is attached under the `attachments[]` array key the backend
        // expects.
        expect(appendSpy).toHaveBeenCalledWith(
            'attachments[]',
            expect.objectContaining({ uri: 'file:///tmp/cert.pdf', name: 'cert.pdf' }),
        );
    });
});
